name: ci

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  BUILD_PLATFORMS: linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          load: true
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max`
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository }}
          path: /tmp/${{ github.repository }}.tar

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.repository }}
          path: /tmp
      - run: docker load --input /tmp/${{ github.repository }}.tar
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: true
          tags: ${{ github.repository }}:latest
