name: ci

on:
  push:
    branches: [ main ]

permissions:
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - run: just build
      - run: just publish
